---
#------------------------------------------------------------------------------
# Self-describing - simple tasks against AWS-hosted EC2 instances.
#------------------------------------------------------------------------------

- hosts: "tag_application_{{ application | replace('-', '_') }}:&tag_category_{{ category | replace('-', '_') }}"
  name: Exploratory tasks
  any_errors_fatal: true

  vars:
    # Some of these would be passed in as extra-vars in an automated build e.g. account id
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: 730918948368-{{ category }}-ssm
    ansible_aws_ssm_region: eu-west-2
    ssm_timeout: 60

    # Aligned with Terraform provider-level tags
    application: iac
    category: vmlab

  tasks:
    - ansible.builtin.debug:
        msg: Greetings from {{ hostvars[ ansible_host ][ 'public_ip_address' ] }}

  post_tasks:
    - ansible.builtin.debug:
        msg: Goodbye from {{ hostvars[ ansible_host ][ 'public_ip_address' ] }}
