---
formatter: markdown table

content: |-
 ## Table of Contents

 - [Requirements][1]
 - [Inputs][2]
 - [Outputs][3]
 - [Modules][4]
 - [Resources][5]

 {{ .Header }}

 {{ .Requirements }}{{"\n"}}
 {{ .Inputs }}{{"\n"}}
 {{ .Outputs }}{{"\n"}}
 {{ .Modules }}{{"\n"}}
 {{ .Resources }}{{"\n"}}
 [1]: #requirements
 [2]: #inputs
 [3]: #outputs
 [4]: #modules
 [5]: #resources

sort:
 enabled: true

output:
 file: README.md
 mode: inject
 template: |-
   <!-- BEGIN_TF_DOCS -->
   {{ .Content }}
   <!-- END_TF_DOCS -->

settings:
 indent: 2
 read-comments: false
 hide-empty: false
