# https://taskfile.dev

version: '3'

tasks:
  tlint:
    desc: Test the Terraform config for formatting, validity and linting
    dir: terraform
    cmds:
      - terraform init -backend=false -upgrade
      - terraform fmt -recursive -diff
      - terraform validate
      - tflint

  tsec:
    desc: Check the Terraform config for security good practices
    dir: terraform
    cmds:
      - tfsec --exclude-downloaded-modules

  tinit:
    desc: Initialise the Terraform configuration
    dir: terraform
    cmds:
      - terraform init

  tplan:
    desc: Create a Terraform plan
    dir: terraform
    cmds:
      - terraform plan -out tf.plan

  tapply:
    desc: Apply the Terraform plan
    dir: terraform
    cmds:
      - terraform apply tf.plan

  tdestroy:
    desc: Destroy the resources in the Terraform state
    dir: terraform
    cmds:
      - terraform destroy -auto-approve

  alint:
    desc: Lint the ansible playbook
    dir: ansible
    cmds:
      - ansible-lint -v playbook.yml
