---
plugin: amazon.aws.aws_ec2

regions:
  - eu-west-2

cache: yes
cache_prefix: aws_ec2

filters:
  instance-state-name: running

keyed_groups:
  - prefix: tag
    key: tags

hostnames:
  - instance-id
  - ip-address
