---
#------------------------------------------------------------------------------
# Self-describing - simple tasks against AWS-hosted EC2 instances.
#------------------------------------------------------------------------------

- hosts: "tag_application_{{ application | replace('-', '_') }}:&tag_category_{{ category | replace('-', '_') }}"
  name: Exploratory tasks
  any_errors_fatal: true
  remote_user: ubuntu

  vars:
    # Aligned with Terraform provider-level tags (pass in as extra vars in a pipeline)
    application: iac
    category: vmlab

    # Used to set the prompt / hostname
    instance_name: "{{ hostvars[inventory_hostname].tags.name }}"

    # TODO check ansible_facts.user_id, ansible_user_id

  tasks:
    - name: Set the hostname to the value of the 'name' tag
      become: yes
      ansible.builtin.hostname:
        name: "{{ instance_name }}"
        use: systemd

    - name: Create Downloads folder
      ansible.builtin.file:
        name: "{{ ansible_env.HOME }}/Downloads/"
        state: directory
        mode: 0750
