---
#------------------------------------------------------------------------------
# Self-describing - simple tasks against AWS-hosted EC2 instances.
#------------------------------------------------------------------------------

- hosts: "tag_application_{{ application | replace('-', '_') }}:&tag_category_{{ category | replace('-', '_') }}"
  name: Exploratory tasks
  any_errors_fatal: true
  remote_user: ubuntu

  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: 730918948368-{{ category }}-ssm  # extra vars in a pipeline
    ansible_aws_ssm_region: eu-west-2
    ssm_timeout: 60

    # Aligned with Terraform provider-level tags (pass in as extra vars in a pipeline)
    application: iac
    category: vmlab

    # Used to set the prompt / hostname
    instance_name: "{{ hostvars[inventory_hostname].tags.name }}"

  tasks:
    - debug:
        msg: FOO

    - name: Set the hostname to the value of the 'name' tag
      become: yes
      ansible.builtin.hostname:
        name: "{{ instance_name }}"
        use: systemd

    - name: Create Downloads folder
      ansible.builtin.file:
        name: "{{ ansible_env.HOME }}/Downloads/"
        state: directory
        mode: 0750
